source 'https://rubygems.org'

gem 'rails', '4.2.3'

gem 'pg'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'slim-rails', '~> 3.0.1'
gem 'kaminari', '~> 0.16.3'

# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

# Caching
gem 'actionpack-page_caching'
gem 'actionpack-action_caching'

# API
gem 'grape', '~> 0.13.0'
gem 'grape_logging', '~> 1.1', '>= 1.1.2'
gem 'grape-swagger', '~> 0.10.2'
gem 'warden', '~> 1.2', '>= 1.2.3'

group :development, :test do
  gem 'byebug'
  gem 'populator'
  gem 'spring'
  gem 'faker'
  gem 'annotate', '~> 2.6.10'
end

group :development do
  gem 'thin'
end
