source 'https://rubygems.org'

gem 'rails', '4.2.3'

gem 'pg'

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'slim-rails', '~> 3.0.1'
gem 'kaminari', '~> 0.16.3'

# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do
  gem 'byebug'
  gem 'populator'
  gem 'spring'
  gem 'faker'
  gem 'annotate', '~> 2.6.10'
end

