source 'http://rubygems.org'

gem "rack"
gem "rack-contrib", "~> 1.1.0"
gem "rake", "~> 0.9.2"
gem "thin"

group :development do
  gem "ruby-prof", "~> 0.11.2"
end

group :test do
  gem "rspec", "~> 2.7.0"
  gem "rack-test", "~> 0.6.0"
  gem "database_cleaner", "~> 0.6.7"
  gem "fuubar"
end
